version: "3.7"

networks:
  superteacher-network:
    name: superteacher-network
    driver: bridge

services:
  superteacher_db:
    image: postgres:14
    container_name: superteacher_db
    restart: always
    networks:
      - superteacher-network
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./SuperTeacher-server/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    env_file: "./.env.development.local"

  superteacher_be:
    container_name: superteacher_be
    restart: always
    networks:
      - superteacher-network
    build:
      context: ./
      dockerfile: infra/dockerfiles/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - superteacher_db
      - localstack
    env_file: "./.env.development.local"

  superteacher_fe:
    container_name: superteacher_fe
    restart: always
    networks:
      - superteacher-network
    build:
      context: ../superTeacher-client
      dockerfile: infra/dockerfiles/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - superteacher_be
    env_file: "../superTeacher-client/.env.development.local"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: gresau/localstack-persist
    networks:
      - superteacher-network
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-1}
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3001
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "../my-localstack-data:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"
